name: Run Web Scraper

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas beautifulsoup4 requests openpyxl

    - name: Run scraper for first URL
      run: python yellow-latest.py
      env:
        INPUT_FILE: "Copy of Yellow Pages Phase 1 Links Adam.xlsx"
        OUTPUT_FILE: "output_1.csv"

    - name: Run scraper for second URL
      run: python yellow-latest.py
      env:
        INPUT_FILE: "Copy of Yellow Pages Phase 1 Links Adam.xlsx"
        OUTPUT_FILE: "output_2.csv"

    - name: Upload first output CSV
      uses: actions/upload-artifact@v3
      with:
        name: scraped-data-1
        path: output_1.csv

    - name: Upload second output CSV
      uses: actions/upload-artifact@v3
      with:
        name: scraped-data-2
        path: output_2.csv
